{
 "title": "Chatterbox Metrics H100",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Avg Batch Size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tts_batcher_avg_batch_size", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tts_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active requests",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tts_active_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Time to First Byte (TTFB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": " histogram_quantile(0.5, rate(tts_time_to_first_byte_seconds_bucket[5m]))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, rate(tts_time_to_first_byte_seconds_bucket[5m]))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "description": "p50 and p90",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(tts_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p50"
    },
    {
     "expr": " histogram_quantile(0.95, rate(tts_request_duration_seconds_bucket[5m]))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Requests / Sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 9, "y": 7 },
   "targets": [
    { "expr": "rate(tts_requests_total[5m])", "legendFormat": "__auto" }
   ]
  }
 ]
}